server:
  port: 8080

knife4j:
  enable: true
  openapi:
    title: 脑筋急转弯API文档
    description: AI聊天接口文档
    version: v1.0
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.ywang.aichat.controller

ai:
  apiKey: da1d4be6-890d-49be-ac4a-ac6b9a414a08

